services:
  - type: web
    name: ice-committee-backend
    env: node
    plan: free
    buildCommand: chmod +x ./build.sh && ./build.sh
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        scope: build
      - key: JWT_SECRET
        scope: build
      - key: CLOUDINARY_CLOUD_NAME
        scope: build
      - key: CLOUDINARY_API_KEY
        scope: build
      - key: CLOUDINARY_API_SECRET
        scope: build
      - key: BREVO_API_KEY
        scope: build
      - key: BREVO_FROM_EMAIL
        scope: build
      - key: BREVO_FROM_NAME
        value: "ICE Committee"
      - key: ADMIN_EMAIL
        scope: build
